### ISSUE TITLE
Undefined rule font-family-no-missing-generic-family-keyword

### ISSUE THREAD

**Issue by per-garden** [roramirez/MagicMirror-Module-Template#11]
Hi, following the template installations instruction I'm attempting to create my own MM-module. I encounter test errors as shown below though:
```html
pi@raspberrypi:~/MagicMirror/modules/MMM-Trains-Trafikverket $ npm test

> MagicMirror-Module-Template@1.2.0 test /home/pi/MagicMirror/modules/MMM-Trains-Trafikverket
> ./node_modules/grunt/bin/grunt

Running "eslint:target" (eslint) task

Running "stylelint:simple" (stylelint) task
Warning: Running stylelint failed
Error: Undefined rule font-family-no-missing-generic-family-keyword                          
  at module.exports (/home/pi/MagicMirror/modules/MMM-Trains-Trafikverket/node_modules/stylelint/lib/utils/configurationError.js:8:27)                                                    
  at Object.keys.forEach.ruleName (/home/pi/MagicMirror/modules/MMM-Trains-Trafikverket/node_modules/stylelint/lib/augmentConfig.js:279:13)                                               
  at Array.forEach (<anonymous>:null:null)                                                   
  at normalizeAllRuleSettings (/home/pi/MagicMirror/modules/MMM-Trains-Trafikverket/node_modules/stylelint/lib/augmentConfig.js:275:29)                                                   
  at augmentConfigBasic.then.then.then.then.augmentedConfig (/home/pi/MagicMirror/modules/MMM-Trains-Trafikverket/node_modules/stylelint/lib/augmentConfig.js:84:12)                      
  at <anonymous>:null:null                                                                   
 Use --force to continue.                                                                    

Aborted due to warnings.


Execution Time (2018-03-16 16:48:34 UTC+1)
loading tasks     1.2s  ââââââââââââ 20%
eslint:target     1.7s  ââââââââââââââââ 27%
stylelint:simple  3.3s  âââââââââââââââââââââââââââââââ 53%
Total 6.2s

npm ERR! Test failed.  See above for more details.
pi@raspberrypi:~/MagicMirror/modules/MMM-Trains-Trafikverket $
```
I use node v9.8.0 and npm 5.6.0

Any workarounds or solutions to get past this?

**Comment by per-garden** [comment]
OK, I solved this:
 1. "stylelint": "^8.3.0" in package.json
 2. npm install
 3. npm prune
 4. npm install
 5. npm test (now running without error)

**Comment by roramirez** [comment]
Maybe should be add this change in package.json. The Pull Request are welcome.
